# Generated by Django 5.0.6 on 2024-06-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user_from', 'user_to')},
        ),
    ]
